# Generated by Django 4.0.4 on 2022-06-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
