# Generated by Django 4.0.4 on 2022-06-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0005_alter_category_options_alter_phrase_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='tag',
            field=models.ManyToManyField(to='phrases.tag'),
        ),
    ]
