# Generated by Django 4.0.4 on 2022-06-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0006_tag_phrase_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='tag',
            new_name='tags',
        ),
    ]
