# Generated by Django 4.0.4 on 2022-06-29 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phrases', '0009_phrase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phrases', to='phrases.category'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='phrases', to='phrases.tag'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phrases', to=settings.AUTH_USER_MODEL),
        ),
    ]
