# Generated by Django 4.0.4 on 2022-06-29 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phrases', '0010_alter_phrase_category_alter_phrase_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrasevotes', to='phrases.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phrasevotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='phrasevote',
            constraint=models.UniqueConstraint(fields=('user', 'phrase'), name='one_vote_per_user_per_phrase'),
        ),
    ]
