# Generated by Django 4.0.4 on 2022-06-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0011_phrasevote_phrasevote_one_vote_per_user_per_phrase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='phrasevote',
            name='one_vote_per_user_per_phrase',
        ),
        migrations.AddConstraint(
            model_name='phrasevote',
            constraint=models.UniqueConstraint(fields=('user', 'phrase'), name='one_vote_per_user_per_phrase'),
        ),
    ]
