# Generated by Django 4.0.4 on 2022-06-24 04:45

from django.db import migrations, models
import jobs.models
from wisdomPhrases.storage_backends import PrivateMediaStorage


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, help_text='PDFs only', storage=PrivateMediaStorage(), upload_to='resumes', validators=[jobs.models.validate_pdf]),
        ),
    ]
